
-- Optional: Create a filegroup and explicity create a set of files
ALTER DATABASE SomeDB
ADD FILEGROUP [USERDATA];  
GO

ALTER DATABASE SomeDB   
ADD FILE (NAME = SomeDB_USERDATA1, FILENAME = 'D:\DB\SomeDB_USERDATA1.ndf', SIZE = 5MB, MAXSIZE = 1000MB, FILEGROWTH = 5MB)    
TO FILEGROUP [USERDATA];  
GO
ALTER DATABASE SomeDB   
ADD FILE (NAME = SomeDB_USERDATA2, FILENAME = 'D:\DB\SomeDB_USERDATA2.ndf', SIZE = 5MB, MAXSIZE = 1000MB, FILEGROWTH = 5MB)    
TO FILEGROUP [USERDATA];  
GO
ALTER DATABASE SomeDB   
ADD FILE (NAME = SomeDB_USERDATA3, FILENAME = 'D:\DB\SomeDB_USERDATA3.ndf', SIZE = 5MB, MAXSIZE = 1000MB, FILEGROWTH = 5MB)    
TO FILEGROUP [USERDATA];  
GO 

-- Create partition function
CREATE PARTITION FUNCTION PF_Year (datetime)
AS RANGE RIGHT FOR VALUES ('20190101', '20200101')
GO

-- Create partition scheme
CREATE PARTITION SCHEME PS_Year
AS PARTITION PF_Quarter ALL TO (SomeDB_USERDATA1, SomeDB_USERDATA2, SomeDB_USERDATA3) 
GO

-- Create table or clustered index
CREATE TABLE SomeTable 
(
	Col1 INT PRIMARY KEY, 
	Col2 NVARCHAR(10)
) ON PS_Year (Col1) ;  
GO 